from datetime import datetime, timezone

from sqlalchemy import text
from geoalchemy2.shape import from_shape
from shapely.geometry import Point

from app.core.database import Base, SessionLocal, engine
from app.models.spill import Spill
from app.models.drift import DriftPoint
from app.models.vessel import Vessel
from app.models.attribution import VesselAttribution
from app.models.origin import SpillOrigin
from app.models.vessel_track import VesselTrackPoint

# The production database starts empty. Enable PostGIS and create all ORM
# tables before running the demo-data migration/seed statements below.
with engine.begin() as connection:
    connection.execute(text("CREATE EXTENSION IF NOT EXISTS postgis"))
Base.metadata.create_all(bind=engine)

db = SessionLocal()

try:
    db.execute(text("ALTER TABLE spills ADD COLUMN IF NOT EXISTS perimeter_km DOUBLE PRECISION"))
    db.execute(text("ALTER TABLE spills ADD COLUMN IF NOT EXISTS compactness DOUBLE PRECISION"))
    db.execute(text("ALTER TABLE spills ADD COLUMN IF NOT EXISTS estimated_age_hours DOUBLE PRECISION"))
    db.commit()

    # Real Sentinel-1 test-scene characterization generated by the local
    # OCEANNOVA U-Net + radiometric filtering pipeline.
    spill = db.query(Spill).filter(Spill.spill_id == "SP-001").first()
    spill_geometry = from_shape(Point(-89.01991595626981, 28.906728514527977), srid=4326)
    acquisition_time = datetime(2018, 9, 26, 0, 0, tzinfo=timezone.utc)

    if not spill:
        spill = Spill(
            spill_id="SP-001",
            confidence=0.9594,
            area_km2=27.0378,
            acquisition_time=acquisition_time,
            perimeter_km=110.53,
            compactness=0.0278,
            estimated_age_hours=None,
            geometry=spill_geometry,
        )
        db.add(spill)
    else:
        spill.confidence = 0.9594
        spill.area_km2 = 27.0378
        spill.acquisition_time = acquisition_time
        spill.perimeter_km = 110.53
        spill.compactness = 0.0278
        spill.estimated_age_hours = None
        spill.geometry = spill_geometry
    db.commit()

    # Representative AIS positions around the reconstructed origin. These
    # are explicitly demonstration tracks, not claimed historical AIS records
    # for the 2018 Sentinel-1 scene.
    vessels = [
        Vessel(mmsi="419001234", vessel_name="OCEAN STAR", latitude=28.845, longitude=-89.155, speed_knots=12.5, course=250.0),
        Vessel(mmsi="419005678", vessel_name="SEA HORIZON", latitude=28.865, longitude=-89.145, speed_knots=9.8, course=250.0),
        Vessel(mmsi="419009876", vessel_name="MARINE EXPRESS", latitude=28.930, longitude=-89.080, speed_knots=15.2, course=250.0),
        Vessel(mmsi="419000111", vessel_name="FAR HORIZON", latitude=31.540, longitude=-84.900, speed_knots=11.0, course=90.0),
    ]
    for vessel in vessels:
        existing = db.query(Vessel).filter(Vessel.mmsi == vessel.mmsi).first()
        if existing:
            existing.vessel_name = vessel.vessel_name
            existing.latitude = vessel.latitude
            existing.longitude = vessel.longitude
            existing.speed_knots = vessel.speed_knots
            existing.course = vessel.course
        else:
            db.add(vessel)
    db.commit()

    # Real AI-derived drift trajectory using the prototype environmental
    # inputs used by drift/real_integration.py. Negative hours are hindcast;
    # positive hours are forecast.
    drift_points = [
        ( -12, 28.852338, -89.153056, 0.300, 65.0, 5.385, 68.2),
        ( -11, 28.856870, -89.141961, 0.300, 65.0, 5.385, 68.2),
        ( -10, 28.861403, -89.130866, 0.300, 65.0, 5.385, 68.2),
        (  -9, 28.865935, -89.119771, 0.300, 65.0, 5.385, 68.2),
        (  -8, 28.870468, -89.108676, 0.300, 65.0, 5.385, 68.2),
        (  -7, 28.875000, -89.097581, 0.300, 65.0, 5.385, 68.2),
        (  -6, 28.879533, -89.086486, 0.300, 65.0, 5.385, 68.2),
        (  -5, 28.884066, -89.075391, 0.300, 65.0, 5.385, 68.2),
        (  -4, 28.888598, -89.064296, 0.300, 65.0, 5.385, 68.2),
        (  -3, 28.893131, -89.053201, 0.300, 65.0, 5.385, 68.2),
        (  -2, 28.897663, -89.042106, 0.300, 65.0, 5.385, 68.2),
        (  -1, 28.902196, -89.031011, 0.300, 65.0, 5.385, 68.2),
        (   0, 28.906729, -89.019916, 0.300, 65.0, 5.385, 68.2),
        (   1, 28.911261, -89.008821, 0.300, 65.0, 5.385, 68.2),
        (   2, 28.915794, -88.997726, 0.300, 65.0, 5.385, 68.2),
        (   3, 28.920326, -88.986631, 0.300, 65.0, 5.385, 68.2),
        (   4, 28.924859, -88.975536, 0.300, 65.0, 5.385, 68.2),
        (   5, 28.929391, -88.964441, 0.300, 65.0, 5.385, 68.2),
        (   6, 28.933924, -88.953346, 0.300, 65.0, 5.385, 68.2),
        (   7, 28.938457, -88.942251, 0.300, 65.0, 5.385, 68.2),
        (   8, 28.942989, -88.931156, 0.300, 65.0, 5.385, 68.2),
        (   9, 28.947522, -88.920061, 0.300, 65.0, 5.385, 68.2),
        (  10, 28.952054, -88.908966, 0.300, 65.0, 5.385, 68.2),
        (  11, 28.956587, -88.897871, 0.300, 65.0, 5.385, 68.2),
        (  12, 28.961119, -88.886776, 0.300, 65.0, 5.385, 68.2),
    ]
    db.query(DriftPoint).filter(DriftPoint.spill_id == "SP-001").delete()
    for hours, lat, lon, current_speed, current_direction, wind_speed, wind_direction in drift_points:
        db.add(DriftPoint(
            spill_id="SP-001",
            latitude=lat,
            longitude=lon,
            hours_from_detection=hours,
            current_speed=current_speed,
            current_direction=current_direction,
            wind_speed=wind_speed,
            wind_direction=wind_direction,
        ))
    db.commit()

    tracks = {
        "419001234": [
            (-6, 28.870, -89.120), (-3, 28.860, -89.140), (0, 28.845, -89.155),
            (3, 28.840, -89.165), (6, 28.835, -89.175),
        ],
        "419005678": [
            (-6, 28.900, -89.100), (-3, 28.880, -89.130), (0, 28.865, -89.145),
            (3, 28.855, -89.160), (6, 28.845, -89.175),
        ],
        "419009876": [
            (-6, 29.000, -89.000), (-3, 28.960, -89.040), (0, 28.930, -89.080),
            (3, 28.900, -89.120), (6, 28.880, -89.150),
        ],
    }
    db.query(VesselTrackPoint).delete()
    for mmsi, points in tracks.items():
        vessel = db.query(Vessel).filter(Vessel.mmsi == mmsi).first()
        for hours, lat, lon in points:
            db.add(VesselTrackPoint(
                mmsi=mmsi,
                timestamp_hours_from_origin=hours,
                latitude=lat,
                longitude=lon,
                speed_knots=vessel.speed_knots if vessel else None,
                course=vessel.course if vessel else None,
            ))
    db.commit()

    # Attribution values from the completed real-AI-to-AIS demonstration run.
    # These are representative AIS evidence scores, not legal responsibility.
    candidate_results = [
        {
            "mmsi": "419001234", "score": 0.9621, "distance": 0.84,
            "time": 0.0, "trajectory": 0.983, "behavior": 0.820,
        },
        {
            "mmsi": "419005678", "score": 0.8774, "distance": 0.74,
            "time": 3.0, "trajectory": 0.985, "behavior": 0.580,
        },
        {
            "mmsi": "419009876", "score": 0.7563, "distance": 3.09,
            "time": 6.0, "trajectory": 0.938, "behavior": 0.310,
        },
    ]

    db.query(VesselAttribution).filter(VesselAttribution.spill_id == "SP-001").delete()
    for item in candidate_results:
        db.add(VesselAttribution(
            id=f"ATTR-{item['mmsi'][-3:]}",
            spill_id="SP-001",
            mmsi=item["mmsi"],
            attribution_score=item["score"],
            distance_km=item["distance"],
            time_difference_hours=item["time"],
            trajectory_match_score=item["trajectory"],
            behavioral_anomaly_score=item["behavior"],
        ))
    db.commit()

    origin = db.query(SpillOrigin).filter(SpillOrigin.spill_id == "SP-001").first()
    origin_geometry = from_shape(Point(-89.153024, 28.852338), srid=4326)
    if origin:
        origin.geometry = origin_geometry
        origin.uncertainty_km = 8.5
        origin.method = "backward_drift_hindcast"
    else:
        db.add(SpillOrigin(
            id="ORIGIN-001",
            spill_id="SP-001",
            geometry=origin_geometry,
            uncertainty_km=8.5,
            method="backward_drift_hindcast",
        ))
    db.commit()

    print("OCEANNOVA complete real-AI investigation demo data updated successfully.")
    print("Pipeline: detect -> characterize -> hindcast/forecast -> AIS filter -> explainable ranking")
finally:
    db.close()
