import { Circle, GeoJSON, MapContainer, Marker, Polyline, Popup, TileLayer, useMap } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import { useEffect, useMemo, useState } from "react";
import type { GeoJsonObject } from "geojson";
import { getSpillGeoJSON, type Investigation, type Vessel } from "../services/api";
interface MapViewProps { investigation: Investigation; darkMode?: boolean; }
delete (L.Icon.Default.prototype as unknown as { _getIconUrl?: unknown })._getIconUrl;
L.Icon.Default.mergeOptions({iconRetinaUrl:"https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",iconUrl:"https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",shadowUrl:"https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png"});
const spillIcon=L.divIcon({className:"spill-marker",html:`<div class="spill-marker-inner"></div>`,iconSize:[30,30],iconAnchor:[15,15]});
const originIcon=L.divIcon({className:"origin-marker",html:`<div class="origin-marker-inner"></div>`,iconSize:[28,28],iconAnchor:[14,14]});
const vesselIcon=L.divIcon({className:"vessel-ship-marker",html:`<div class="vessel-ship-icon">🚢</div>`,iconSize:[42,42],iconAnchor:[21,21],popupAnchor:[0,-18]});
function points(i:Investigation):[number,number][]{const p:[number,number][]=[[i.centroid.lat,i.centroid.lon]];if(i.origin)p.push([i.origin.latitude,i.origin.longitude]);i.drift.forEach(d=>p.push([d.latitude,d.longitude]));return p;}
function Camera({investigation}:{investigation:Investigation}){const map=useMap();useEffect(()=>{map.fitBounds(L.latLngBounds(points(investigation)),{padding:[35,35],maxZoom:9,animate:false})},[map,investigation]);return null;}
function vesselPopup(v:Vessel){const rep=v.relevance!=="filtered";return <div className="vessel-popup"><strong>🚢 {v.vessel_name??v.mmsi}</strong><span className="popup-provenance">{rep?"REPRESENTATIVE DEMO CANDIDATE":"FILTERED AIS TRAFFIC"}</span><div>Attribution score: <b>{v.attribution_score.toFixed(1)}%</b></div><div>Distance from origin: {v.distance_km==null?"—":`${v.distance_km.toFixed(1)} km`}</div><div>Time difference: {v.time_difference_hours==null?"—":`${v.time_difference_hours.toFixed(1)} h`}</div>{rep&&<small>No historical AIS claim — corroboration required.</small>}</div>}
function VesselPanel({vessels}:{vessels:Vessel[]}){const ranked=useMemo(()=>[...vessels].sort((a,b)=>b.attribution_score-a.attribution_score).slice(0,4),[vessels]);return <aside className="vessel-attribution-panel"><div className="vessel-panel-head"><div><span className="vessel-panel-kicker">MARITIME ANALYSIS</span><h3>Vessel Attribution <small>(Demo Dataset)</small></h3></div><button className="panel-info" title="Attribution is not proof of guilt">i</button></div><p className="vessel-panel-subtitle">Potential vessels near the spill with attribution scores based on proximity, temporal correlation, trajectory and behavioral analysis.</p><div className="vessel-ranking">{ranked.map((v,index)=>{const score=Math.max(0,Math.min(100,v.attribution_score));const level=score>=90?"high":score>=75?"medium":"low";return <div className={`vessel-rank-card ${level}`} key={v.mmsi}><div className="vessel-rank-number">{index+1}</div><div className="vessel-rank-icon">🚢</div><div className="vessel-rank-main"><strong>{v.vessel_name??v.mmsi}</strong><div className="vessel-details"><span>Distance from origin <b>{v.distance_km==null?"—":`${v.distance_km.toFixed(1)} km`}</b></span><span>Time difference <b>{v.time_difference_hours==null?"—":`${v.time_difference_hours.toFixed(1)} hours`}</b></span><span>Trajectory match <b>{score>=85?"High":score>=65?"Medium":"Low"}</b></span><span>Behavioral anomaly <b>{score>=85?"Yes":score>=65?"Possible":"No"}</b></span></div><div className="vessel-score-track"><i style={{width:`${score}%`}}/></div><em>Representative Demo Candidate</em></div><b className="vessel-score">{score.toFixed(1)}%</b></div>})}</div><div className="vessel-panel-note"><span>i</span><p>These vessels are shown as representative candidates from the provided dataset. Attribution scores indicate likelihood based on available evidence, not proof of guilt.</p></div></aside>}
export default function MapView({investigation,darkMode=true}:MapViewProps){const[spillGeoJson,setSpillGeoJson]=useState<GeoJsonObject|null>(null);useEffect(()=>{let active=true;setSpillGeoJson(null);getSpillGeoJSON(investigation.spill_id).then(d=>{if(active)setSpillGeoJson(d)}).catch(console.error);return()=>{active=false}},[investigation.spill_id]);const spill:[number,number]=[investigation.centroid.lat,investigation.centroid.lon];const origin=investigation.origin?[investigation.origin.latitude,investigation.origin.longitude] as [number,number]:null;const drift=investigation.drift.map(d=>[d.latitude,d.longitude] as [number,number]);return <MapContainer center={spill} zoom={7} scrollWheelZoom style={{height:"100%",width:"100%"}}><TileLayer attribution={darkMode?"Tiles © Esri":"© OpenStreetMap contributors"} url={darkMode?"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}":"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"}/><Camera investigation={investigation}/><div className="map-layer-button">▱ &nbsp; Map Layers</div><div className="map-zoom-controls"><button onClick={()=>{}}>+</button><button onClick={()=>{}}>-</button><button>⌾</button></div>{spillGeoJson&&<GeoJSON data={spillGeoJson} style={()=>({color:"#ff3d45",weight:2.5,opacity:1,fillColor:"#d72d25",fillOpacity:.34})}><Popup><strong>Detected Oil Spill</strong><br/>Sentinel-1 SAR · AI segmentation<br/>Predicted footprint: {investigation.area_km2.toFixed(2)} km²</Popup></GeoJSON>}<Marker position={spill} icon={spillIcon}><Popup><strong>Detected Oil Spill</strong><br/>Confidence: {(investigation.confidence*100).toFixed(1)}%</Popup></Marker>{origin&&<><Circle center={origin} radius={(investigation.origin?.uncertainty_km??8)*1000} pathOptions={{color:"#ffb000",fillOpacity:.08,weight:2,dashArray:"7 6"}}/><Marker position={origin} icon={originIcon}/></>}{drift.length>1&&<Polyline positions={drift} pathOptions={{weight:4,opacity:.9}}/>}{investigation.vessels.map(v=>v.latitude==null||v.longitude==null?null:<Marker key={v.mmsi} position={[v.latitude,v.longitude]} icon={vesselIcon}><Popup>{vesselPopup(v)}</Popup></Marker>)}<VesselPanel vessels={investigation.vessels}/><div className="map-legend"><strong>MAP LEGEND</strong><span>🔴 Detected Oil Spill (AI)</span><span>🚢 Vessel — attribution candidate</span><span>┄ Vessel trajectory</span></div><div className="map-scale">20 km</div></MapContainer>}
