import type { GeoJsonObject } from "geojson";
const PRODUCTION_API="https://oceannova-api.onrender.com/api/v1";
const DATA_ROOT="https://cdn.jsdelivr.net/gh/Deepanshu779/OCEANNOVA@main/data/processed/all_scenes";
const MANIFEST_URL=`${DATA_ROOT}/manifest.json?v=20260911`;
const configuredApi=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,"");
const API_BASE_URL=import.meta.env.PROD?PRODUCTION_API:(configuredApi||"http://127.0.0.1:8000/api/v1");
export interface Coordinates{lat:number;lon:number}
export interface Origin{latitude:number;longitude:number;uncertainty_km:number;method?:string|null}
export interface DriftPoint{latitude:number;longitude:number;hours_from_detection:number;current_speed?:number|null;current_direction?:number|null;wind_speed?:number|null;wind_direction?:number|null}
export interface Vessel{mmsi:string;vessel_name?:string|null;latitude?:number|null;longitude?:number|null;speed_knots?:number|null;course?:number|null;attribution_score:number;distance_km?:number|null;time_difference_hours?:number|null;proximity_score?:number|null;temporal_score?:number|null;trajectory_match_score?:number|null;behavioral_anomaly_score?:number|null;relevance?:string}
export interface VesselTrackPoint{mmsi:string;timestamp_hours_from_origin:number;latitude:number;longitude:number;speed_knots?:number|null;course?:number|null}
export interface SpillCharacterization{area_km2:number;perimeter_estimate_km?:number|null;compactness_estimate?:number|null;estimated_age_hours?:number|null;age_status:string}
export interface TrafficSummary{total_vessels_considered:number;filtered_irrelevant:number;ranked_candidates:number;filtering_rule:string}
export interface Investigation{spill_id:string;confidence:number;area_km2:number;centroid:Coordinates;characterization:SpillCharacterization;origin?:Origin|null;drift:DriftPoint[];traffic:TrafficSummary;vessels:Vessel[];vessel_tracks:VesselTrackPoint[]}
export interface DatasetScene{incident_id?:string|null;scene_id:string;file:string;split:"train"|"test";has_image:boolean;has_mask:boolean;image_path:string}
const COMMITTED_SCENES:DatasetScene[]=Array.from({length:21},(_,i)=>{const id=`SP-${String(i+1).padStart(3,"0")}`;return{incident_id:id,scene_id:id,file:`${id} · processed Sentinel-1 SAR`,split:"train",has_image:true,has_mask:true,image_path:`${DATA_ROOT}/${id}`}});
async function request<T>(path:string):Promise<T>{const r=await fetch(`${API_BASE_URL}${path}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`OCEANNOVA API ${r.status}: ${path}`);return(await r.json())as T}
async function dataJson<T>(spillId:string,filename:string):Promise<T>{const r=await fetch(`${DATA_ROOT}/${encodeURIComponent(spillId)}/${filename}?v=20260911`,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Radar_data ${spillId}/${filename}: ${r.status}`);return(await r.json())as T}
async function committedInvestigation(spillId:string):Promise<Investigation>{const data=await dataJson<any>(spillId,"characterization.json");const d=data.detection??{};const c=data.centroid??d.centroid??{};if(typeof c.latitude!=="number"||typeof c.longitude!=="number")throw new Error(`Radar_data ${spillId} has no centroid`);return{spill_id:data.incident_id??spillId,confidence:Number(d.mean_ai_confidence??0),area_km2:Number(d.area_km2??0),centroid:{lat:Number(c.latitude),lon:Number(c.longitude)},characterization:{area_km2:Number(d.area_km2??0),perimeter_estimate_km:d.perimeter_km??null,compactness_estimate:d.compactness??null,estimated_age_hours:null,age_status:"not_available_from_single_radar_scene"},origin:null,drift:[],traffic:{total_vessels_considered:0,filtered_irrelevant:0,ranked_candidates:0,filtering_rule:"Historical AIS not loaded"},vessels:[],vessel_tracks:[]}}
export async function getInvestigation(spillId:string):Promise<Investigation>{try{return await committedInvestigation(spillId)}catch(e){console.warn(`Radar_data artifact unavailable for ${spillId}; using API`,e);return request<Investigation>(`/radar/spills/${encodeURIComponent(spillId)}/investigation`)}}
export async function getSpillGeoJSON(spillId:string):Promise<GeoJsonObject>{try{return await dataJson<GeoJsonObject>(spillId,"spill.geojson")}catch(e){console.warn(`Radar_data GeoJSON unavailable for ${spillId}; using API`,e);return request<GeoJsonObject>(`/radar/spills/${encodeURIComponent(spillId)}/geojson`)} }
export async function getDatasetScenes():Promise<DatasetScene[]>{const fallback=new Map(COMMITTED_SCENES.map(s=>[s.incident_id!,s]));try{const manifest=await fetch(MANIFEST_URL,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json()});for(const item of manifest.scenes??[]){if(item.incident_id&&fallback.has(item.incident_id))fallback.set(item.incident_id,{incident_id:item.incident_id,scene_id:item.scene_id,file:String(item.source?.image??"").split(/[\\/]/).pop()??"",split:item.split,has_image:true,has_mask:Boolean(item.source?.ground_truth),image_path:String(item.source?.image??"").replaceAll("\\","/")})}}catch(e){console.warn("Radar_data manifest unavailable; keeping complete committed inventory",e)}return Array.from(fallback.values()).sort((a,b)=>(a.incident_id??"").localeCompare(b.incident_id??""))}
