"""
OCEANNOVA
Real AI + Drift -> AIS Attribution Integration

Uses the probable spill origin generated by the real
Sentinel-1 AI pipeline and evaluates historical AIS
candidate vessels.

IMPORTANT:
The AIS tracks used here are demonstration tracks.
They are not claimed to be historical AIS records for
the 2018 Sentinel-1 scene.
"""

from pathlib import Path
import json
import math


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DRIFT_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "ai_predictions"
    / "SP-001_real_drift.json"
)

OUTPUT_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "ai_predictions"
    / "SP-001_real_attribution.json"
)


# ============================================================
# DEMONSTRATION AIS CANDIDATES
# ============================================================

VESSELS = [

    {
        "mmsi": "419001234",
        "name": "OCEAN STAR",
        "behavior": 0.82,
        "expected_course": 250,
        "track": [
            [-6, 28.870, -89.120],
            [-3, 28.860, -89.140],
            [0, 28.845, -89.155],
            [3, 28.840, -89.165],
            [6, 28.835, -89.175],
        ],
    },

    {
        "mmsi": "419005678",
        "name": "SEA HORIZON",
        "behavior": 0.58,
        "expected_course": 250,
        "track": [
            [-6, 28.900, -89.100],
            [-3, 28.880, -89.130],
            [0, 28.865, -89.145],
            [3, 28.855, -89.160],
            [6, 28.845, -89.175],
        ],
    },

    {
        "mmsi": "419009876",
        "name": "MARINE EXPRESS",
        "behavior": 0.31,
        "expected_course": 250,
        "track": [
            [-6, 29.000, -89.000],
            [-3, 28.960, -89.040],
            [0, 28.930, -89.080],
            [3, 28.900, -89.120],
            [6, 28.880, -89.150],
        ],
    },

    {
        "mmsi": "419000111",
        "name": "FAR HORIZON",
        "behavior": 0.12,
        "expected_course": 90,
        "track": [
            [-6, 31.500, -85.000],
            [-3, 31.520, -84.950],
            [0, 31.540, -84.900],
            [3, 31.560, -84.850],
            [6, 31.580, -84.800],
        ],
    },
]


# ============================================================
# GEO
# ============================================================

EARTH_RADIUS_KM = 6371.0


def haversine_km(
    lat1,
    lon1,
    lat2,
    lon2
):

    lat1 = math.radians(lat1)
    lat2 = math.radians(lat2)

    dlat = lat2 - lat1

    dlon = math.radians(
        lon2
        - lon1
    )

    a = (
        math.sin(dlat / 2) ** 2
        +
        math.cos(lat1)
        * math.cos(lat2)
        * math.sin(dlon / 2) ** 2
    )

    return (
        2
        * EARTH_RADIUS_KM
        * math.asin(
            math.sqrt(a)
        )
    )


def proximity_score(
    distance_km,
    radius_km=50
):

    return max(
        0.0,
        min(
            1.0,
            1.0
            - distance_km
            / radius_km
        )
    )


def temporal_score(
    hours,
    window=12
):

    return max(
        0.0,
        min(
            1.0,
            1.0
            - abs(hours)
            / window
        )
    )


def bearing(
    lat1,
    lon1,
    lat2,
    lon2
):

    lat1 = math.radians(lat1)
    lat2 = math.radians(lat2)

    dlon = math.radians(
        lon2 - lon1
    )

    y = math.sin(dlon) * math.cos(lat2)

    x = (
        math.cos(lat1)
        * math.sin(lat2)
        -
        math.sin(lat1)
        * math.cos(lat2)
        * math.cos(dlon)
    )

    angle = math.degrees(
        math.atan2(y, x)
    )

    return (
        angle + 360
    ) % 360


def trajectory_score(
    track,
    origin_lat,
    origin_lon
):

    distances = []

    for point in track:

        hour = point[0]
        lat = point[1]
        lon = point[2]

        distance = haversine_km(
            lat,
            lon,
            origin_lat,
            origin_lon
        )

        distances.append(
            distance
        )

    closest = min(
        distances
    )

    return max(
        0.0,
        min(
            1.0,
            1.0
            - closest / 50
        )
    ), closest


# ============================================================
# ATTRIBUTION
# ============================================================

def score_vessel(
    vessel,
    origin_lat,
    origin_lon
):

    track = vessel["track"]

    trajectory_match, closest_distance = (
        trajectory_score(
            track,
            origin_lat,
            origin_lon
        )
    )

    closest_index = min(
        range(len(track)),
        key=lambda i:
        haversine_km(
            track[i][1],
            track[i][2],
            origin_lat,
            origin_lon
        )
    )

    closest_point = track[
        closest_index
    ]

    closest_time = closest_point[0]

    temporal = temporal_score(
        closest_time
    )

    proximity = proximity_score(
        closest_distance
    )

    behavior = vessel[
        "behavior"
    ]

    score = (
        0.35 * proximity
        +
        0.20 * temporal
        +
        0.30 * trajectory_match
        +
        0.15 * behavior
    )

    return {

        "mmsi": vessel["mmsi"],

        "vessel": vessel["name"],

        "attribution_score": round(
            score * 100,
            2
        ),

        "distance_km": round(
            closest_distance,
            3
        ),

        "time_difference_hours": (
            closest_time
        ),

        "proximity_score": round(
            proximity,
            4
        ),

        "temporal_score": round(
            temporal,
            4
        ),

        "trajectory_match_score": round(
            trajectory_match,
            4
        ),

        "behavioral_anomaly_score": round(
            behavior,
            4
        ),

        "relevance": (
            "high"
            if score >= 0.70
            else
            "medium"
            if score >= 0.45
            else
            "low"
        )
    }


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 75)
    print(
        "OCEANNOVA - REAL AI TO AIS ATTRIBUTION"
    )
    print("=" * 75)

    with open(
        DRIFT_FILE,
        "r",
        encoding="utf-8"
    ) as f:

        drift = json.load(f)

    origin = drift[
        "origin"
    ]

    origin_lat = float(
        origin["latitude"]
    )

    origin_lon = float(
        origin["longitude"]
    )

    uncertainty = float(
        origin["uncertainty_km"]
    )

    print()
    print("PROBABLE SPILL ORIGIN")
    print("-" * 75)

    print(
        f"Latitude    : "
        f"{origin_lat:.6f}"
    )

    print(
        f"Longitude   : "
        f"{origin_lon:.6f}"
    )

    print(
        f"Uncertainty : "
        f"±{uncertainty:.1f} km"
    )

    # --------------------------------------------------------
    # Score candidates
    # --------------------------------------------------------

    results = []

    for vessel in VESSELS:

        result = score_vessel(
            vessel,
            origin_lat,
            origin_lon
        )

        results.append(
            result
        )

    results.sort(
        key=lambda x:
        x["attribution_score"],
        reverse=True
    )

    print()
    print("AIS CANDIDATE RANKING")
    print("-" * 75)

    for rank, result in enumerate(
        results,
        start=1
    ):

        print(
            f"{rank}. "
            f"{result['vessel']} "
            f"({result['mmsi']})"
        )

        print(
            f"   Attribution : "
            f"{result['attribution_score']:.2f}%"
        )

        print(
            f"   Distance    : "
            f"{result['distance_km']:.2f} km"
        )

        print(
            f"   Time delta  : "
            f"{result['time_difference_hours']:+.1f} h"
        )

        print(
            f"   Proximity   : "
            f"{result['proximity_score']:.3f}"
        )

        print(
            f"   Trajectory  : "
            f"{result['trajectory_match_score']:.3f}"
        )

        print(
            f"   Behavior    : "
            f"{result['behavioral_anomaly_score']:.3f}"
        )

        print()

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    output = {

        "incident_id": (
            drift["incident_id"]
        ),

        "origin": origin,

        "method": {

            "type": (
                "explainable AIS attribution"
            ),

            "weights": {

                "proximity": 0.35,
                "temporal": 0.20,
                "trajectory": 0.30,
                "behavior": 0.15
            }
        },

        "data_status": (
            "demonstration_AIS_tracks"
        ),

        "ranked_candidates": results
    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            output,
            f,
            indent=2
        )

    print("=" * 75)
    print("AIS ATTRIBUTION COMPLETE")
    print("=" * 75)

    print(
        f"Candidates evaluated: "
        f"{len(results)}"
    )

    print(
        f"Top candidate: "
        f"{results[0]['vessel']}"
    )

    print(
        f"Score: "
        f"{results[0]['attribution_score']:.2f}%"
    )

    print()
    print(
        f"✓ Saved: {OUTPUT_FILE}"
    )


if __name__ == "__main__":
    main()