"""Convert a clipped NOAA AIS CSV into OCEANNOVA attribution evidence.

Usage from repository root:
    python ais/run_noaa_real_attribution.py data/real/ais/SP-001_noaa_ais.csv

The script intentionally fails closed: it never labels representative tracks as
real. A result generated by this script is marked REAL_NOAA_AIS.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from backend.data_sources.noaa_ais import filter_origin_window, group_tracks, load_csv, haversine_km

ORIGIN_LAT = 28.852338
ORIGIN_LON = -89.153024
ORIGIN_TIME = datetime(2018, 9, 26, 0, 0, tzinfo=timezone.utc)
OUT = Path("data/processed/ai_predictions/SP-001_real_noaa_ais.json")


def score_track(points, origin_lat: float, origin_lon: float, origin_time: datetime) -> dict:
    nearest = min(points, key=lambda p: haversine_km(p.latitude, p.longitude, origin_lat, origin_lon))
    distance = haversine_km(nearest.latitude, nearest.longitude, origin_lat, origin_lon)
    dt_hours = (nearest.timestamp - origin_time).total_seconds() / 3600.0
    proximity = max(0.0, min(1.0, 1.0 - distance / 50.0))
    temporal = max(0.0, min(1.0, 1.0 - abs(dt_hours) / 12.0))
    # For real NOAA track points, trajectory consistency is represented by the
    # closest approach inside the origin window; the existing attribution
    # engine can add richer motion features later without changing this schema.
    trajectory = proximity
    behavior = 0.0
    score = 0.35 * proximity + 0.20 * temporal + 0.30 * trajectory + 0.15 * behavior
    return {
        "mmsi": nearest.mmsi,
        "vessel": nearest.vessel_name or "UNKNOWN",
        "attribution_score": round(score * 100, 2),
        "distance_km": round(distance, 3),
        "time_difference_hours": round(dt_hours, 2),
        "proximity_score": round(proximity, 4),
        "temporal_score": round(temporal, 4),
        "trajectory_match_score": round(trajectory, 4),
        "behavioral_anomaly_score": behavior,
        "relevance": "high" if score >= 0.70 else "medium" if score >= 0.45 else "low",
        "evidence": "NOAA MarineCadastre historical AIS position inside origin window",
    }


def main(path: str) -> None:
    points = load_csv(path)
    relevant = filter_origin_window(points, ORIGIN_LAT, ORIGIN_LON, ORIGIN_TIME)
    tracks = group_tracks(relevant)
    ranked = sorted(
        (score_track(track, ORIGIN_LAT, ORIGIN_LON) for track in tracks.values()),
        key=lambda item: item["attribution_score"],
        reverse=True,
    )
    result = {
        "incident_id": "SP-001",
        "data_status": "REAL_NOAA_AIS",
        "source": {
            "provider": "NOAA Office for Coastal Management / MarineCadastre",
            "dataset": "AIS Vessel Tracks 2018",
            "source_url": "https://ocmgeodatastor1.blob.core.windows.net/marinecadastre/ais/aistrack/AISVesselTracks2018.zip",
        },
        "origin": {"latitude": ORIGIN_LAT, "longitude": ORIGIN_LON, "timestamp": ORIGIN_TIME.isoformat()},
        "filter": {"radius_km": 50, "hours_before": 12, "hours_after": 12},
        "input_points": len(points),
        "relevant_points": len(relevant),
        "vessels_considered": len(ranked),
        "ranked_candidates": ranked,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps({"output": str(OUT), "vessels_considered": len(ranked), "top_candidate": ranked[0] if ranked else None}, indent=2))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python ais/run_noaa_real_attribution.py <clipped_noaa_ais.csv>")
    main(sys.argv[1])
